### ISSUE TITLE
Support for CDN's which use relative URLS

### ISSUE THREAD

**Issue by ThaDaVos** [feat-agency/vite-plugin-webfont-dl#17]
It seems it breaks when relative urls are used, as an example: https://cdn.jsdelivr.net/npm/@mdi/font@7.x/css/materialdesignicons.min.css
Uses a relative url to the font files like `url("../fonts/materialdesignicons-webfont.eot?v=7.0.96")` which seems to break as the full relative path is just copied over to the webfonts.css - but vite than fails to load these - at least during HMR

**Comment by 0xb4lint** [comment]
Thanks @ThaDaVos!
It's fixed in [v3.1.2](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.1.2).

**Comment by ThaDaVos** [comment]
Thanks for the fix, will try to check this Monday! Maybe, you can also look into the issue of no HTML file?

**Comment by ThaDaVos** [comment]
https://github.com/feat-agency/vite-plugin-webfont-dl/issues/15
