### ISSUE TITLE
Fonts are loaded in development but failing on build

### ISSUE THREAD

**Issue by jahermosilla** [feat-agency/vite-plugin-webfont-dl#2]
It seems that there's a problem (At least with Chrome) when the project is built.

> The resource xxx.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

It seems that adding ``rel="stylesheet preload"`` instead of ``rel="preload"`` at [this line](https://github.com/feat-agency/vite-plugin-webfont-dl/blob/4bd80f951594a59b8eb986022a90093343156985/src/css-injector.ts#L5) solves the problem.

**Comment by 0xb4lint** [comment]
`rel="stylesheet preload"` is not a valid parameter according to https://www.w3.org/TR/preload/

besides that, only the generated `webfonts.css` is preloaded, the fonts are not

could you please paste the generated, dist `index.html`?
