### ISSUE TITLE
cssContent.replaceAll issue

### ISSUE THREAD

**Issue by marDonchev** [feat-agency/vite-plugin-webfont-dl#21]
Hello. 
I have this setup in my project
**index.html**
...
```
<link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap"
            rel="stylesheet"
        />
```
...
And a standard setup of the plugin.
However when running "serve" I get the following issue:
`[webfont-dl] https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap[webfont-dl] cssContent.replaceAll is not a function`
Can you tell me if there is something I'm doing wrong?

Thanks

**Comment by 0xb4lint** [comment]
Hi @marDonchev!

I just created a repo using this command: `npm create vite@latest vue-ts-webfont -- --template vue-ts`.
After that I added this plugin along with your snippet: https://github.com/0xb4lint/vue-ts-webfont/commit/e3ac2c3f38378914d0ecff687e9259a1f4fbddbf.

The `npm run dev` command works as expected.

Could you please tell me how you use Vite or maybe create a repo to demonstrate the issue?

Thanks!

**Comment by marDonchev** [comment]
I will think how can I present the code, but probably it is important to note that I haven't used the npm create. 
I have migrated my project from webpack to vite following some simple instructions I found online. 
Everything else seems to be working fine except this plugin that I've setup manually. 
Is there anything specifically that I have to do in order to avoid this message?
(one of the key change was to move the index.html file from /public to the root folder of the project - not sure if it makes a difference). 

Thanks

**Comment by 0xb4lint** [comment]
It seems there's an issue on your side with downloading the CSS from Google.

After this line:
```
[webfont-dl] https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap
```

There should be the following one:
```
[webfont-dl] ✓ 1 css downloaded.
```

Instead of this you have:
```
[webfont-dl] cssContent.replaceAll is not a function
```

That means there's an error happened inside the try-catch block: https://github.com/feat-agency/vite-plugin-webfont-dl/blob/master/src/index.ts#L259

The error message `replaceAll is not a function` implicates the  `cssContent` variable is not a string.

Do you have proxy setting that might cause this? Could you try fetching the CSS with curl?
```
curl -vvv "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap"
```

**Comment by marDonchev** [comment]
Hm ... strange... my curl can download the file normally.
Could it be a non-ascii character somewhere in the url?

This is my output:
```
curl -vvv "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap"
*   Trying 172.217.17.138:443...
* Connected to fonts.googleapis.com (172.217.17.138) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=upload.video.google.com
*  start date: Dec 12 08:19:17 2022 GMT
*  expire date: Mar  6 08:19:16 2023 GMT
*  subjectAltName: host "fonts.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap]
* h2h3 [:scheme: https]
* h2h3 [:authority: fonts.googleapis.com]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x13480a800)
> GET /css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;700&display=swap HTTP/2
> Host: fonts.googleapis.com
> user-agent: curl/7.85.0
> accept: */*
>
< HTTP/2 200
< content-type: text/css; charset=utf-8
< access-control-allow-origin: *
< timing-allow-origin: *
< expires: Tue, 17 Jan 2023 16:30:24 GMT
< date: Tue, 17 Jan 2023 16:30:24 GMT
< cache-control: private, max-age=86400
< cross-origin-opener-policy: same-origin-allow-popups
< cross-origin-resource-policy: cross-origin
< server: ESF
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
< vary: Accept-Encoding
<
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/montserrat/v25/JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtr6Ew-.ttf) format('truetype');
}
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/montserrat/v25/JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCu170w-.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  font-stretch: normal;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/opensans/v34/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0C4n.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 700;
  font-stretch: normal;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/opensans/v34/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1y4n.ttf) format('truetype');
}
* Connection #0 to host fonts.googleapis.com left intact
```

**Comment by 0xb4lint** [comment]
@marDonchev I've just released `3.4.4-beta.0` with additional logging regarding the CSS downloading.

Could you please try it and send the output?

**Comment by marDonchev** [comment]
Hi, @0xb4lint. 
Sorry for the delay of my answer. 
Attached is the screenshot of the output. 
Does it matter that I'm running it with node v14?
Should I test with other versions of node?

![webfont-dl-screenshot](https://user-images.githubusercontent.com/45700323/214409485-4a087715-6f0f-44e5-b826-f30f5be069c9.png)

**Comment by 0xb4lint** [comment]
Wow, you are right! `replaceAll` is only supported from Node 15.

**Comment by marDonchev** [comment]
Ok. Let me try with node16 and will post the result here :)

**Comment by marDonchev** [comment]
It seems to be working fine with node16. 
Howerever I see duplication in the log messages. Might be due to using the beta version of the package. 
![image](https://user-images.githubusercontent.com/45700323/214419164-22f0c41e-549c-4c1f-b16e-38951c4c91d0.png)

**Comment by 0xb4lint** [comment]
I'm happy you can finally use this plugin!
Now you can use the non-beta version and there won't be any issue with the logs. 😉

**Comment by marDonchev** [comment]
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
