### ISSUE TITLE
[Feature Request] Adobe TypeKit Support

### ISSUE THREAD

**Issue by fluxism** [feat-agency/vite-plugin-webfont-dl#22]
Adobe TypeKit fonts are not currently supported.

**Comment by 0xb4lint** [comment]
Unfortunately, Adobe TypeKit is not an open-source service, like Google Fonts.

> **Can I host the web font files on my own server?**
> No. Adobe doesn't offer the ability to locally host fonts. Our web font hosting delivers fonts from a globally-distributed content delivery network (CDN), which performs much better and is more scalable than using local hosting for static assets.

https://helpx.adobe.com/fonts/using/font-licensing.html

**Comment by 0xb4lint** [comment]
(However, soon we'll release [Fontshare](https://www.fontshare.com) support.)

**Comment by Jogai** [comment]
Can I request cdnfonts.com too?

**Comment by 0xb4lint** [comment]
Yes, sure @Jogai! 
I'll release cdnfonts.com support with v3.5.0!

**Comment by 0xb4lint** [comment]
@Jogai you can try out the CDNFonts support with [`v3.5.0-beta.1`](https://www.npmjs.com/package/vite-plugin-webfont-dl/v/3.5.0-beta.1)

**Comment by Jogai** [comment]
Vite 4 logs `[webfont-dl] Request failed with status code 403`, switching to bunny fonts works.

**Comment by 0xb4lint** [comment]
It seems CDNFonts is using Cloudflare with bot detection, making it almost impossible to fetch fonts from them. 😔

**Comment by Jogai** [comment]
That's too bad. Still, its nice that bunny works. I'm happy as a rabbit ;)
