### ISSUE TITLE
Q: It downloads the font in each build?

### ISSUE THREAD

**Issue by antoniogiroz** [feat-agency/vite-plugin-webfont-dl#23]
Hello!

I'm checking this plugin to use in my project, but I can see each time the build is launched download all the fonts time after time. Is it right?

If so, do you plan to implement a possible cache?

Thanks!

**Comment by 0xb4lint** [comment]
Hi @antoniogiroz!
Actually that's a pretty good idea, thank you!
I'll research this topic! 😉

**Comment by 0xb4lint** [comment]
I've just released [`v3.6.0`](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.6.0) with a file-based persistent cache feature. 😉
