### ISSUE TITLE
`MIME type ('') is not a supported stylesheet` error in Vite development-mode

### ISSUE THREAD

**Issue by cewald** [feat-agency/vite-plugin-webfont-dl#25]
If I use the library in `vite`'s dev-mode, the following error is thrown in the browser and therefor won't load the `webfont.css` file:  `Refused to apply style from 'https://domain.com/@webfonts/webfonts.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

It is working in production mode though.
The files are available and can be loaded by calling the URL directly.
I'm using the versions `vite-plugin-webfont-dl@3.6.4` and `vite@4.1.4`.

These are the request-headers in development-mode:
<img width="407" alt="Bildschirm­foto 2023-04-02 um 19 28 24" src="https://user-images.githubusercontent.com/6112764/229369018-dec12f72-185d-4d22-9cb9-fc9f4c938a8f.png">

Compared to those in production-mode:
<img width="413" alt="Bildschirm­foto 2023-04-02 um 19 25 04" src="https://user-images.githubusercontent.com/6112764/229368869-2479e8fd-64db-4da6-99f5-8348f174c357.png">
a7d0982.png">

Does this sound familiar?

**Comment by 0xb4lint** [comment]
Hi @cewald!

You are absolutely right, thanks for raising this issue!
It required a small `Content-Type: text/css` fix, which has been done. 😉 

You can check it with [`v3.6.5`](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.6.5) release.

**Comment by cewald** [comment]
This was fast! Awesome. I already was about to post the bugfix. Thank you :)
