### ISSUE TITLE
read: ECONNRESET

### ISSUE THREAD

**Issue by SeryiBaran** [feat-agency/vite-plugin-webfont-dl#26]
Hello!

Sometimes there is a `read: ECONNRESET` error, what should I do?

Pastebin with logs:
https://pastebin.com/S7DWSZ9P

Url is correct.

No config, google fonts included via link:css (variant a from readme).

**Comment by 0xb4lint** [comment]
Hi @SeryiBaran!

`ECONNRESET` means some communication issue happened between the server and the client.

What happens if you run the build again? Or if you open `https://fonts.gstatic.com/s/opensans/v34/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk_RkWVAewA.woff2` in your browser?

I'll try to make these error messages more declarative and maybe create some retry functionality.

**Comment by SeryiBaran** [comment]
> What happens if you run the build again?

Error occurs again

> What happens if you run the build again? Or if you open https://fonts.gstatic.com/s/opensans/v34/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk_RkWVAewA.woff2 in your browser?

The browser downloads the file

**Comment by SeryiBaran** [comment]
Hmm, I'm restart build again and all works without errors 🤯

In any case, thanks for your response!

**Comment by 0xb4lint** [comment]
It could be related to your network, your router, your ISP, or some IP restriction / traffic shaping from the server.

**Comment by SeryiBaran** [comment]
Maybe due to the fact that a lot of files are downloading in one time?

If you run build many times (it turns out that the fonts are downloaded in pieces), the error disappears

**Comment by 0xb4lint** [comment]
That could be an issue!
I'm working on some retry with a random waiting time downloading mechanism.

**Comment by 0xb4lint** [comment]
@SeryiBaran could you please try out version `3.7.0-beta.0`? it has some detailed logging and retry on error functionality

**Comment by SeryiBaran** [comment]
Fonts loads successfully after several attempts, thank you!

https://pastebin.com/T1KXuTdN
