### ISSUE TITLE
 connect ETIMEDOUT

### ISSUE THREAD

**Issue by Jucabelve** [feat-agency/vite-plugin-webfont-dl#27]
Hello, first of all, thank you very much for the plugin, it has been very functional for me. 

For the past three days, I have been experiencing this issue: 

![image](https://user-images.githubusercontent.com/36972766/230712260-d62c36b6-5645-4c06-ab68-4c01d7caef71.png)

Apparently, this IPv6 address belongs to Chilean Google servers (I assume that it is trying to download the fonts from there due to Google's global load balancer, I´m in Perú). 

A ping to this ip shows this:

![image](https://user-images.githubusercontent.com/36972766/230712315-229042a7-aac5-4c50-aaa6-9b363cb707e4.png)

and in the DevTools, chrome is showing this:

![image](https://user-images.githubusercontent.com/36972766/230712382-4a596605-9cfb-4628-bc99-09646509cc13.png)

The application works normally, but the fonts aren't loading. I haven't made any changes, I just resumed development and this issue appeared, I assume that the issue is not directly related to the plugin, but rather with not being able to find the font host in the service.

I am using:

Node **v18.25.0**
React **v18.2.0**
Vite **v4.2.1**

Thanks.

**Comment by 0xb4lint** [comment]
Hi @Jucabel!

This plugin is using [`axios`](https://github.com/feat-agency/vite-plugin-webfont-dl/blob/master/src/downloader.ts#L46-L57) in the background. 

What do you think, forcing IPv4 would solve this issue?

(Another possible solution might be using [Bunny Fonts](https://fonts.bunny.net) as a drop-in replacement for Google Fonts.)

**Comment by 0xb4lint** [comment]
I've just released [`v3.7.1-beta.0`](https://www.npmjs.com/package/vite-plugin-webfont-dl/v/3.7.1-beta.0) with [forced IPv4](https://github.com/feat-agency/vite-plugin-webfont-dl/commit/580c85dd684989d6915d76c67b63e98eda8c539c) download, could you please check it?

**Comment by Jucabelve** [comment]
> I've just released [`v3.7.1-beta.0`](https://www.npmjs.com/package/vite-plugin-webfont-dl/v/3.7.1-beta.0) with [forced IPv4](https://github.com/feat-agency/vite-plugin-webfont-dl/commit/580c85dd684989d6915d76c67b63e98eda8c539c) download, could you please check it?

Got it, @0xb4lint , It works fine with [v3.7.1-beta.0](https://www.npmjs.com/package/vite-plugin-webfont-dl/v/3.7.1-beta.0) 

I guess It was a problem with the IPv6.

Thank you so much.

**Comment by 0xb4lint** [comment]
Thanks for the confirmation!

I'll release v3.7.1 later today. 😉
