### ISSUE TITLE
Regression when using "type": "module" in package.json in 3.7.1

### ISSUE THREAD

**Issue by MrBazlow** [feat-agency/vite-plugin-webfont-dl#29]
Latest release introduced an unhandled error when package.json is set to ECMAScript modules mode.

`this.cacheDir = resolve(__dirname, "../.cache/");`
`ReferenceError: __dirname is not defined in ES module scope`

Demo:
* 3.7.0 - https://stackblitz.com/edit/vitejs-vite-8ckfs4?file=README.md
* 3.7.1 - https://stackblitz.com/edit/vitejs-vite-47bz4v?file=README.md

**Comment by 0xb4lint** [comment]
Hi @MrBazlow!

Sorry for the inconvenience and thanks for raising this issue!

I've just fixed this issue with [`v3.7.2`](https://www.npmjs.com/package/vite-plugin-webfont-dl/v/3.7.2).
