### ISSUE TITLE
Sveltekit support

### ISSUE THREAD

**Issue by amr3k** [feat-agency/vite-plugin-webfont-dl#38]
This plugin does not work with sveltekit!

Here's a [stackblitz repro](https://stackblitz.com/edit/sveltejs-kit-template-default-bxkyhg?file=src%2Froutes%2F%2Bpage.svelte)

Please run `npm run build && npm run preview`

**Comment by 0xb4lint** [comment]
Unfortunately there's no support for `transformIndexHtml` Vite hook, which is essential for this plugin.

More info: https://github.com/sveltejs/kit/discussions/8269

**Comment by Radiergummi** [comment]
So, AFAICT, the `transformIndexHtml` hook is required to inject the style tag and parse the `link` tags, right? But if we configure the font link manually, and disable `injectAsStyleTag` there should be a way to import the fonts, no?

This issue probably shouldn't be closed yet.

**Comment by Radiergummi** [comment]
For anyone else ending up at this issue -- I spent way too long trying to hack Sveltekit support into the library, and finally ended up using [Fontsource](https://fontsource.org) instead, which allows you to install Google fonts as npm packages. Until Sveltekit adds support for `transformIndexHtml`, this is probably your best bet.
