### ISSUE TITLE
Disable logging for cached fonts

### ISSUE THREAD

**Issue by Radiergummi** [feat-agency/vite-plugin-webfont-dl#41]
Currently, the plugin will write a line to the log every time it serves a font - even if it will be fetched from the file cache. This feels a bit verbose in my opinion. I'd like to suggest only logging the first time a webfont file is fetched from its origin, and maybe introduce debug logging with more specific log messages.  
Would you accept a PR that achieves this?

**Comment by 0xb4lint** [comment]
Thanks for raising this issue @Radiergummi!

That line should be just a [flash](https://github.com/feat-agency/vite-plugin-webfont-dl/blob/master/src/logger.ts#L34) and it should clear the line after [500ms](https://github.com/feat-agency/vite-plugin-webfont-dl/blob/master/src/logger.ts#L50-L52).

Anyway, I've [moved](https://github.com/feat-agency/vite-plugin-webfont-dl/commit/069f448a1e9004341e0c1ea26d1c743e55da6953) the `flashLine()` call after the cache check, so it should be called only if download starting.

Just released `v3.8.0`!

**Comment by Radiergummi** [comment]
I'm running Vite in a container, where the output is appended to a log, thus clearing doesn't work - but it's good to know!

Anyway, that's awesome, thank you for the quick fix!
