### ISSUE TITLE
[Feature Request] Embed fonts inline using base64

### ISSUE THREAD

**Issue by hannojg** [feat-agency/vite-plugin-webfont-dl#43]
Hey,

I have a project where I need to bundle all code of the web app into a single `index.html` file. I'd like to use this plugin. Instead of bundling the fonts as separate assets, we can base64 them and put them directly into the style tag / font face definition.

Do you think that'd be possible? Thanks in advance for the response 🌟

**Comment by 0xb4lint** [comment]
Hi @hannojg!

Actually that's a great idea! 😉 

Added `embedFonts` option with `v3.9.0`.
