### ISSUE TITLE
Error: ENAMETOOLONG

### ISSUE THREAD

**Issue by Bartek20** [feat-agency/vite-plugin-webfont-dl#53]
I'm trying to implement this plugin but I get following error on build:
```
Error: ENAMETOOLONG: name too long, open '/workspaces/ZSM TimeTable Remastered/dist/assets/KFOlCnqEu92Fr1MmWUlvBgWiKOPUvaFiVlWbMWgtUADtbNE0F3PS6kya0xphlyZ8mDc6o4iQFKK5F3VtZ5PdjfZ_8WTjahT6xxR7j2h3bRSa7eyYwKotUoNKq6EbiFJFNtx-MlRaH0Pbyi9IAKm4b4tC1at0vpVnWrmBWbBATH43zlZ1M1pr8P3LlT2EmqG8uoFcoUYwBiRBfsH63m446w06pvPmdmvFfakXe2vboUxl5MrTwUVLmEjibRkXBdlwaP_0XgZ0MyYPHHQOoCP8K4uphim2aip_prwVU_F_0BqgljLd2QBzVBkThQSLR9fhM5Q2lRNXGYL5GuOC5XYhYy7aPm_jrMRwKRvb8AUCcO_XlCphU0WeWe2aIGmgzPQPdqo9D97QYlu6k1Luj6ieFHEm-BYxvyBtr.woff2'
```
This is the font url: https://fonts.googleapis.com/css2?display=swap&text=0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ%C4%85%C4%84%C4%87%C4%86%C4%99%C4%98%C5%82%C5%81%C5%84%C5%83%C3%B3%C3%93%C5%9B%C5%9A%C5%BA%C5%B9%C5%BC%C5%B9.%28%29%2C%2F%22-%26%3A&family=Roboto+Condensed:wght@400;700&family=Roboto:wght@400;700

I'm using text parameter to decrease font size and without it everything works propertly.

**Comment by Bartek20** [comment]
Adding embedFonts: true seems to bypass this error but at the same time embedFonts doesn't embed fonts, just puts original url as src in @font-face.

**Comment by 0xb4lint** [comment]
Hi @Bartek20!

Thanks for the issue, I've fixed it! 😉 

Check out `v3.9.4`.
