### ISSUE TITLE
Link preload as font

### ISSUE THREAD

**Issue by HummingMind** [feat-agency/vite-plugin-webfont-dl#61]
Hello,
Would it be possible to add an option to generate a `<link rel="preload" href="fontname.woff2" as="font" type="font/woff2" crossorigin>` style preload links? So the font download starts sooner?

Thank you.

**Comment by 0xb4lint** [comment]
Hello @HummingMind!

In the webfont CSS there could be a lot of font version definitions (different charsets, weights, styles) like in this: https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap

However, typically only 1 or 2 of these variations are actually used, as browsers automatically fetch the required `woff2` files based on the characters and styles displayed on the website.

Preloading all font versions can negatively impact website performance.
