### ISSUE TITLE
Allow Vite to exit with non-zero code when plugin execution fails

### ISSUE THREAD

**Issue by jnoordsij** [feat-agency/vite-plugin-webfont-dl#63]
(First of all thanks a lot for this plugin!)

When running my Vite build with this plugin, I ran into some troubles with compatibility with Yarn, causing this plugin to not succeed at producing assets. However, I first did not notice this, as the only thing notifying me of the fact was a single output line while the Vite build still showed as success.

My suspicion is this is due to the broad `catch` in `generateBundle`, Vite is not alerted of the error and thus proceeds as if build succeeded. I would like to have a way to ensure Vite is made aware of the error in some way, either by some configuration option or by enforcing this as default.

*Note:* I locally worked around the originating issue by using `yarn unplug` and submitted #62 to fix it.

**Comment by 0xb4lint** [comment]
Hi @jnoordsij!

Thanks for raising this issue!

Indeed, there's a try-catch block in the `generateBundle` function that could potentially suppress errors. The goal is to prevent the build from hanging due to issues with a webfont CSS or font download. 

In the worst-case scenario, everything remains the same, and no webfonts are downloaded.

Thanks again for the #62, you can try out with `3.10.0-beta.0`

**Comment by jnoordsij** [comment]
Can confirm the beta works indeed, thanks for that!

I understand that not failing by default might be the preferred option, as indeed preventing the build from working on just the webfonts might be a little harsh. But for some cases, it might be the preferred outcome.

For my usecase, I build Vite assets in a CI pipeline for my Laravel application. If the fonts are missing and I reference the css in my Laravel template, the page won't load as Laravel will throw an exception for referencing a non-existing css file. Therefore I really want the build job to fail if any part of it fails, even the fonts.

My suggestion would be to have some configurable option, e.g. `throwOnError`, that defaults to `false`, but when enabled would rethrow the caught error instead of just logging it. Would that be something you'd accept a PR on?

**Comment by 0xb4lint** [comment]
I understand your use-case, and the `throwOnError` or just `throwError` sounds very reasonable.

I would appreciate if you could create a PR for this!
