### ISSUE TITLE
webfont-dl not caching fonts

### ISSUE THREAD

**Issue by psynyde** [feat-agency/vite-plugin-webfont-dl#7]
I'm using [vite-plugin-webfont-dl](https://github.com/feat-agency/vite-plugin-webfont-dl) on a vite + vue3 project but it seems that fonts aren't caching when i'm using the plugin
here's a deployment `without` vite-plugin-webfont-dl: 

[https://vue-blog-ddx2qgapj-simplyvoid.vercel.app/](https://vue-blog-ddx2qgapj-simplyvoid.vercel.app/)

and here `with` vite-plugin-webfont-dl:

[https://simplyvoid.vercel.app](https://simplyvoid.vercel.app/)

refresh to see the difference..

**Comment by 0xb4lint** [comment]
Hi @SimplyVoid!

The plugin itself doesn't have any effect on your webserver's cache settings.

You can set your config to cache the generated/versioned assets with the following regex:
`\.(?:[0-9a-f]{8})\.(?:css|js)`
