### ISSUE TITLE
[FR] respect manifest setting

### ISSUE THREAD

**Issue by vandres** [feat-agency/vite-plugin-webfont-dl#9]
I am having a setup, where the entry point is not a static index.html but a server generated file. (Craft CMS).

To make that work, I am using the manifest setting of Vite 

```js
    build: {
        emptyOutDir: true,
        manifest: true,
        outDir: '../web/static/',
    },
```

That generated a file like this:

```json
{
  "index.html": {
    "file": "assets/index.c18ecf21.js",
    "src": "index.html",
    "isEntry": true,
    "css": [
      "assets/index.079e947d.css"
    ]
  }
}
```

I would love to see the generated webfont.css in the css-index too, like:

```json
{
  "index.html": {
    "file": "assets/index.c18ecf21.js",
    "src": "index.html",
    "isEntry": true,
    "css": [
      "assets/index.079e947d.css",
      "assets/webfonts.e0bb4bd3.css"
    ]
  }
}
```

Is that somehow already possible? If not, I would like to submit a feature request for it.

**Comment by 0xb4lint** [comment]
Hi @vandres!

We've managed to resolve this issue by releasing [`v3.0.0`](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.0.0).

**Comment by vandres** [comment]
Thank you very much! Already using it :)
